### ISSUE TITLE
Mobile Issues

### ISSUE THREAD

**Issue by RedstoneDaedalus** [HyperCoder2975/typicalbot-website#2]
1.) Navbar dropdown is broken for small screen sizes.
2.) Documentation is completely broken for small screen sizes.

https://imgur.com/a/WLFZJ
https://imgur.com/a/x3Sh2

**Comment by TobiasFeld22** [comment]
Should have been fixed in [06056bc39c095e93f6d12f4bbb4ce1ccf2de079e]
