### ISSUE TITLE
Donation Page Issue

### ISSUE THREAD

**Issue by RedstoneDaedalus** [HyperCoder2975/typicalbot-website#3]
The donation page's custom styling doesn't seem to be working, making the slider in the wrong position and not have a track.

https://imgur.com/a/35IIG

**Comment by TobiasFeld22** [comment]
I made the modifications, but because the donation page is a php file, We will have to wait until hyper implements it. 
https://gist.github.com/TobiasFeld22/e05c2f04c1d55f4755e13df5f5d217b4
